name: ultron
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

executables:
  ultron: main

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  args: ^2.3.0
  collection: ^1.15.0
  get_it: ^7.2.0
  process: ^4.2.4
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0

